# Generated by Django 5.2.17 on 2026-08-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pricelist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Bekliyor'), ('APPROVED', 'Onaylandı'), ('COMPLETED', 'Tamamlandı'), ('PAID', 'Ödendi'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20),
        ),
    ]
