# Generated by Django 5.2.17 on 2026-08-18 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='% olarak', max_digits=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payout_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Yüzdelik'), ('FIXED_PER_SESSION', 'Seans Başı Sabit'), ('HYBRID', 'Hibrit')], default='PERCENTAGE', max_length=20),
        ),
        migrations.CreateModel(
            name='ArtistPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_turnover', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('salon_cut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PAID', 'Ödendi'), ('CANCELLED', 'İptal')], default='DRAFT', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_notes', models.TextField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Nakit'), ('CREDIT_CARD', 'Kredi Kartı'), ('TRANSFER', 'Havale/EFT'), ('SPLIT', 'Parçalı')], default='CASH', max_length=20)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('COMPLETED', 'Tamamlandı'), ('REFUNDED', 'İade Edildi')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('artist_commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('studio_cut_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.appointment')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
