# Generated by Django 5.2.17 on 2026-08-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_artistleave_artistshift_artistworkinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
